### ISSUE TITLE
требуется обновление под текущую версию trinitycore

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Autobalance_for_NPCBots#1]
ну или обновление под https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots т.к имеется куча конфликтов при компилировании.

Заранее спасибо

**Comment by Parkan1986** [comment]
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	LNK1181	не удается открыть входной файл "..\game\Release\game.lib"	worldserver	E:\build\src\server\worldserver\LINK	1	
Ошибка (активно)	E0135	class "Creature" не содержит члена "CustomData"	game	E:\TrinityCore-3.3.5-with-NPCBots\src\server\game\Entities\Creature\AutoBalance.cpp	299	
Ошибка (активно)	E0135	class "Creature" не содержит члена "CustomData"	game	E:\TrinityCore-3.3.5-with-NPCBots\src\server\game\Entities\Creature\AutoBalance.cpp	687	
Ошибка (активно)	E0135	class "Creature" не содержит члена "CustomData"	game	E:\TrinityCore-3.3.5-with-NPCBots\src\server\game\Entities\Creature\AutoBalance.cpp	1116	
Ошибка	C2039	"CustomData": не является членом "Creature".	game	E:\TrinityCore-3.3.5-with-NPCBots\src\server\game\Entities\Creature\AutoBalance.cpp	299	
Ошибка	C2039	"CustomData": не является членом "Creature".	game	E:\TrinityCore-3.3.5-with-NPCBots\src\server\game\Entities\Creature\AutoBalance.cpp	687	
Ошибка	C2039	"CustomData": не является членом "Creature".	game	E:\TrinityCore-3.3.5-with-NPCBots\src\server\game\Entities\Creature\AutoBalance.cpp	1116

**Comment by trickerer** [comment]
У тебя не пропатчился Creature.h `include "CustomData.h"`, так как подразумевалось сначала накладывать автобаланс, а потом уже ботов.

Попробуй с max fuzz 2: `patch -p1 -F 2 < Autobalance.patch`

**Comment by Parkan1986** [comment]
Я несовсем понял как это сделать как Вы рекомендуете, но я вроде исправил свою ошибку и все скомпилировалось.

**Comment by trickerer** [comment]
https://github.com/trickerer/Autobalance_for_NPCBots/commit/f1659d0d00c5841d4dd839a02aaf2e2f92c60717
