### ISSUE TITLE
Запрос:Нужно обновление под текущую версию trinitycore

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Autobalance_for_NPCBots#2]
При установке патча автобаланса происходит конфликт:
Auto-merging src/server/game/Scripting/ScriptMgr.cpp
CONFLICT (content): Merge conflict in src/server/game/Scripting/ScriptMgr.cpp

Конфликт происходит в 18 строчках.Если сделать автоматическое исправление то конфликт пропадает,но в игре начинают проявляется странности, вроде такого что мобы перестают практически наносить мили урон(хотя магический урон наноситься большой).

Пробовал установить этот патч как на оригинальные исходники trinitycore так и на https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots

Заранее спасибо за возможное обновление

**Comment by trickerer** [comment]
Вывод от применения патча. Что там с уроном - просмотрим.

```
$ patch -p1 < AutoBalance.patch
patching file src/server/game/Entities/Creature/AutoBalance.cpp
patching file src/server/game/Entities/Creature/AutoBalance.h
patching file src/server/game/Entities/Creature/Creature.cpp
patching file src/server/game/Entities/Creature/Creature.h
patching file src/server/game/Entities/Creature/CustomData.h
patching file src/server/game/Entities/Unit/Unit.cpp
Hunk #1 succeeded at 6438 (offset 38 lines).
patching file src/server/game/Entities/Unit/Unit.h
Hunk #1 succeeded at 494 (offset 1 line).
patching file src/server/game/Maps/Map.h
patching file src/server/game/Scripting/ScriptMgr.cpp
Hunk #5 succeeded at 2134 with fuzz 1 (offset -6 lines).
Hunk #6 succeeded at 2382 (offset -6 lines).
patching file src/server/game/Scripting/ScriptMgr.h
Hunk #3 succeeded at 442 (offset -6 lines).
Hunk #4 succeeded at 964 (offset -6 lines).
Hunk #5 succeeded at 1107 (offset -6 lines).
patching file src/server/game/World/World.cpp
Hunk #2 succeeded at 2079 (offset 3 lines).
patching file src/server/worldserver/worldserver.conf.dist
Hunk #1 succeeded at 4125 (offset 17 lines).
```
```
$ patch -p1 < AutoBalance-bots.patch
patching file src/server/game/Entities/Creature/AutoBalance.cpp
patching file src/server/game/Entities/Creature/AutoBalance.h
patching file src/server/game/Entities/Creature/Creature.cpp
patching file src/server/game/Entities/Creature/Creature.h
patching file src/server/game/Entities/Creature/CustomData.h
patching file src/server/game/Entities/Unit/Unit.cpp
Hunk #1 succeeded at 6632 (offset 49 lines).
patching file src/server/game/Entities/Unit/Unit.h
Hunk #1 succeeded at 494 (offset 1 line).
patching file src/server/game/Maps/Map.h
patching file src/server/game/Scripting/ScriptMgr.cpp
Hunk #5 succeeded at 2142 with fuzz 1 (offset -6 lines).
Hunk #6 succeeded at 2390 (offset -6 lines).
patching file src/server/game/Scripting/ScriptMgr.h
Hunk #3 succeeded at 444 (offset -6 lines).
Hunk #4 succeeded at 966 (offset -6 lines).
Hunk #5 succeeded at 1109 (offset -6 lines).
patching file src/server/game/World/World.cpp
Hunk #2 succeeded at 2079 (offset 3 lines).
patching file src/server/worldserver/worldserver.conf.dist
Hunk #1 succeeded at 4396 (offset -3 lines).
```

**Comment by Parkan1986** [comment]
Вообще играя с автобалансом урон от мобов работает как то непонятно или даже криво.К примеру при таких вот настройках:
AutoBalance.PlayerChangeNotify = 1

AutoBalance.CountNpcBots = 1
    
AutoBalance.MinHPModifier = 0.01
  
AutoBalance.MinManaModifier = 0.01

AutoBalance.MinDamageModifier = 0.01

В первых локациях мобы бьют мили уроном как бы обычно 1-2 единицы и скаждыйм уровнем урон через уровень-два повышаеться на единицу.Но например бывают случаи что стоят рядом два одинаковых моба начинаешь бить одного моба он наносит урон 1-2 единицы,убив моба переходишь бить другого у второго моба первая атака наносит 10-25 и выше урона,потом моб бывает не наносит урона вообще или типа промахивается,а затем начинает наносить либо стандартный урон 1-2 единицы либо немного повышенный 2-4 единицы при чем не критами.

При этом имея в команде одного бота уроны от мобов вроде нормальные но все равно переодически косячат высоким либо слишком заниженный уроном,а если иметь в команде больше ботов то мобы бывает по игроку и ботам не наносят урона вообще либо нанесут один крупный урон одной атакой(первая атака примерно раз в 20 больше чем обычное нанесение урона и затем мобы либо не наносят урона либо наносят слабый.

Другая проблема с магическими атаками от кастеров.бывает такое что кастеры могут наносить небольшой урон (10-30 единиц)когда с игроком в команде 1 бот и бывало такое что урон при команде с 2мя ботами и выше взлетало до 150-200 и выше за 1 атаку.такая же ситуация с мобами которые используют заклинания ближнего боя,они могут нанести небольшой урон а рядом такой же моб с таким же названием и ИД может нанести урон в 5-10 раз больше.

**Comment by trickerer** [comment]
Выложи полный конфиг автобаланса и напиши на каких мобах тестил

**Comment by Parkan1986** [comment]
Добавлю еще кое-какие наблюдения:
1.Проходя локацию одну уровня 1-10 мобы более-менее наносили урон в ближнем бою плюс небольшие огрехи были с повышенным х10-20 уроном от мобов
2.Перейдя в другую локацию 1-10 при этом мой герой уже 15 уровня мобы перестали наносить обычный урон за исключением урона от кастеров и случайного повышенного уроно от первой атаки.
3.Перейдя в локацию 20-30 уровня мобы  наносят нормальный урон(11 единиц от каждой атаки,плюс иногда повышенный урон не криты от 1ой первой атаки а затем обычный урон(11 единиц) либо урон критами(22-30 единиц)

**Comment by Parkan1986** [comment]
AutoBalance.enable = 1
AutoBalance.Announce.enable = 1
AutoBalance.InflectionPoint = 0.5
AutoBalance.InflectionPointHeroic = 0.5
AutoBalance.InflectionPointRaid10M = 0.5
AutoBalance.InflectionPointRaid10MHeroic = 0.5
AutoBalance.InflectionPointRaid25M = 0.5
AutoBalance.InflectionPointRaid25MHeroic = 0.5
AutoBalance.InflectionPointRaid = 0.5
AutoBalance.InflectionPointRaidHeroic = 0.5
AutoBalance.BossInflectionMult = 1.0
AutoBalance.levelScaling = 1
AutoBalance.levelHigherOffset = 0
AutoBalance.levelLowerOffset  = 0
AutoBalance.levelUseDbValuesWhenExists = 1
AutoBalance.LevelEndGameBoost = 1
AutoBalance.DungeonScaleDownXP = 0
AutoBalance.DungeonsOnly = 0
AutoBalance.PlayerChangeNotify = 1
AutoBalance.CountNpcBots = 1
AutoBalance.MinHPModifier = 0.01
AutoBalance.MinManaModifier = 0.01
AutoBalance.MinDamageModifier = 0.01
AutoBalance.rate.global = 1.0
AutoBalance.rate.health = 1.0
AutoBalance.rate.mana   = 1.0
AutoBalance.rate.armor  = 1.0
AutoBalance.rate.damage = 1.0
AutoBalance.playerCountDifficultyOffset = 0

Мобы:Frostmane troll whelp(милишник),frostmane novice(кастер),ragged young wolf,small crag boar(локация 1-10)
Thistlefur Shaman(caster\melee),Thistlefur Avenger(melee) локация 20-30.

Ради интереса решил потестировать одну фичу.в Дб World в таблице Creature_template поставил минимальный и максимальный уровень всем мобам на 80ый.
Так вот есть кое-какие интресные результаты.От любых мобов на текущем уровне(17)мобы с разных локаций что с 1-10 что с 20-30 в ближнем бою наносят урон от 13 до 18 без критов и иногда со сверхуроном(раза в 3-4),криты обычно если и наносятся то урон в 2 раза больше становиться.
Какие-то кастеры с локации 1-10 магический урон наносят 1-2 единицы(типа Frostmane Novice),мобы кастеры другого типа наносят каст заклинаниями 8-10 урона.(Grik'nik the Cold)
Мобы с локации 20-30 в ближнем наносят 13-18 урона,доп урон каст и дебафов по 7-12 урона Thistlefur Shaman и Thistlefur Avenger

Тестирую дальше.Возможно автобаланс криво повышает статы мобам которые имеют низкий уровень и более-менее занижают статы мобам которые имеют уровень выше чем игрок.

**Comment by trickerer** [comment]
https://github.com/trickerer/Autobalance_for_NPCBots/commit/f301d01e408a1cc4b50b1bfae7d601fe4ea259c0

Пробуй

**Comment by Parkan1986** [comment]
Небольшой тест показал что вроде урон в ближнем бою стал нормальным,а вот урон от кастеров вроде завышен.на 21 уровне урон от кастеров от 200 и выше,вроде это много.

**Comment by trickerer** [comment]
Ок

Магический урон завтра поковыряю

**Comment by Parkan1986** [comment]
Ну да при персонаже на 60ом уровне на 4 сложности vas difficultysettings=4 мобы кастеры бьют по 4,5к урона ну это как бы оочень много

Спасибо что обновляете и поддерживаете модификацию

**Comment by trickerer** [comment]
https://github.com/trickerer/Autobalance_for_NPCBots/commit/af6a22006968b8e51b0209fee612bafc271119f8

**Comment by trickerer** [comment]
Остается дефект размера скалирования урона от кол-ва игроков. Так как тринити использует другую систему базового урона для мобов (урон растет по довольно крутой кривой с уровнем) мобы с балансом могут наносить не большой урон при 1 игроке и почти полный при 2 игроках. Пока не знаю как это решить. Видимо нужна другая формула для расчета балансного урона.

**Comment by Parkan1986** [comment]
После обновления урон от кастеров и милишников стал вроде более-менее адекватным.
Добавлю еще пару наблюдений об автобалансе.
1.Почему то если не поставить AutoBalance.CountNpcBots = 1 на 0 то настройки по типу 
AutoBalance.rate.global = 1.0
AutoBalance.rate.health = 1.0
AutoBalance.rate.mana = 1.0
AutoBalance.rate.armor = 1.0
AutoBalance.rate.damage = 1.0
не дают никакого эффекта,т.е не увеличивают хп,урон,броню и тд.,даже если менять параметр AutoBalance.playerCountDifficultyOffset = 0 на какое-либо другое значение,а если играть с AutoBalance.CountNpcBots = 1 и менять выше перечисленные параметры то начинается влияние.
2.Так же при включенном автобалансе параметры в конфиге вот эти:
Rate.Creature.Normal.HP          = 1
Rate.Creature.Elite.Elite.HP     = 1
Rate.Creature.Elite.RARE.HP      = 1
Rate.Creature.Elite.RAREELITE.HP = 1
Rate.Creature.Elite.WORLDBOSS.HP = 1
не дают никакого влияния,не на увеличение,не на уменьшение.А вот параметры отвечающие за урон от мили и спеллов влияют.
Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 1
Rate.Creature.Elite.RARE.SpellDamage      = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1

Rate.Creature.Normal.Damage          = 1
Rate.Creature.Elite.Elite.Damage     = 1
Rate.Creature.Elite.RARE.Damage      = 1
Rate.Creature.Elite.RAREELITE.Damage = 1
Rate.Creature.Elite.WORLDBOSS.Damage = 1
По крайней мере параметры отвечающие за спелл урон(например Rate.Creature.Normal.SpellDamage ) при уменьшение данного параметра влияли на мобов кастеров и хоть как то резали чрезмерный урон на низких уровнях

**Comment by Parkan1986** [comment]
Тест на двух локациях показал что после исправлений почему-то параметры отвечающие за урон,перестали что-то либо менять у мобов.
Такие параметры как
Rate.Creature.Normal.SpellDamage = 1
Rate.Creature.Elite.Elite.SpellDamage = 1
Rate.Creature.Elite.RARE.SpellDamage = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1

Rate.Creature.Normal.Damage = 1
Rate.Creature.Elite.Elite.Damage = 1
Rate.Creature.Elite.RARE.Damage = 1
Rate.Creature.Elite.RAREELITE.Damage = 1
Rate.Creature.Elite.WORLDBOSS.Damage = 1

AutoBalance.rate.global = 1.0
AutoBalance.rate.damage = 1.0

**Comment by trickerer** [comment]
https://github.com/trickerer/Autobalance_for_NPCBots/commit/19e3c8c01c55a79b7ee2397a60e7d6f283803bcc

Больше никакой магии с вычислением разницы урона через разницу уровня.
ХП теперь должно скалироваться, дамаг тоже.

Обращаю внимание, что параметры обычного урона обновляются только при старте сервера:
Rate.Creature.Normal.Damage  
Rate.Creature.Elite.Elite.Damage  
Rate.Creature.Elite.RARE.Damage  
Rate.Creature.Elite.RAREELITE.Damage  
Rate.Creature.Elite.WORLDBOSS.Damage

**Comment by Parkan1986** [comment]
А как теперь будет скалироваться урон и хп?

**Comment by trickerer** [comment]
ХП нормальным образом, а урон будет ставиться какой должен быть у типичного моба выбранного уровня. Урон от спеллов не изменяется, так как у большинства мобских спеллов урон и так зависит от уровня кастера, конечно возможны эксцессы.

**Comment by Parkan1986** [comment]
а таблица creature_classlevelstats будет иметь влияние на мобов?
Почему спрашиваю,для теста я немного изменил эту таблицу и сделал урон нарастающий у мобов с каждый уровнем.Хоть я еще для теста замедлил прокачку,разницу по получению урона от мобов между 15-19 уровнями я не увидел.Т.е обычные мобы на локациях наносят урон где то 14-19 элитные мобы в данжах от 23 до 30.Единственные что очень много наносили урона это боссы подземелий(например подеземелье Deadmines),мобы и мини боссы наносят урон от 25 до 40 а вот финальный босс бил довольно таки сильно по 100 урона от мили и где то по 50 от способностей.При условии что в команде у меня кроме моего персонажа два бота.

**Comment by trickerer** [comment]
Будет.

Ещё раз: мили урон расчитывается так же как если бы ты просто зашёл на локацию с мобами твоего уровня.

**Comment by Parkan1986** [comment]
Хорошо,буду тестировать.Спасибо за исправление.

**Comment by trickerer** [comment]
Пока будем считать что проблема решена.

**Comment by Parkan1986** [comment]
Да пока все работает отлично без каких-либо проблем.
