### ISSUE TITLE
Вопрос по моду.

### ISSUE THREAD

**Issue by Parkan1986** [trickerer/Autobalance_for_NPCBots#3]
Возможно ли сделать так чтобы изменения в этих строчках 
Rate.Creature.Normal.HP          = 1
Rate.Creature.Elite.Elite.HP     = 1
Rate.Creature.Elite.RARE.HP      = 1
Rate.Creature.Elite.RAREELITE.HP = 1
Rate.Creature.Elite.WORLDBOSS.HP = 1
влияли на  хп мобов при включенном автобалансе/скалировании что в открытом мире то и в подземельях?
Если менять такие параметры в автобалансе 
AutoBalance.rate.global = 1.0
AutoBalance.rate.health = 1.0
AutoBalance.rate.mana   = 1.0
AutoBalance.rate.armor  = 1.0
AutoBalance.rate.damage = 1.0
то они будут влиять на всех мобов даже боссов,а вот строчки
Rate.Creature.Normal.Damage          = 1
Rate.Creature.Elite.Elite.Damage     = 1
Rate.Creature.Elite.RARE.Damage      = 1
Rate.Creature.Elite.RAREELITE.Damage = 1
Rate.Creature.Elite.WORLDBOSS.Damage = 1 и
Rate.Creature.Normal.SpellDamage          = 1
Rate.Creature.Elite.Elite.SpellDamage     = 1
Rate.Creature.Elite.RARE.SpellDamage      = 1
Rate.Creature.Elite.RAREELITE.SpellDamage = 1
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 1
вот эти строчки влияют на урон при включеноом автобалансе и скалировании мобов как в открытом мире так и в подземельях у мобов отдельных категорий.

**Comment by trickerer** [comment]
Посмотрим

**Comment by Parkan1986** [comment]
Спасибо,работает.
