### ISSUE TITLE
unused parameter ‘firstLogin’ and other things

### ISSUE THREAD

**Issue by Juggalo187** [trickerer/Autobalance_for_NPCBots#5]
I used your npcbots repo and applying your autobalance causes build issue on github. Build checks fail or whatever.

To fix it I had to remove `-DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"` from `cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DBUILD_TESTING=1` in the file .github/workflows/gcc-build.yml

This shows the errors https://github.com/Juggalo187/TrinityCore-3.3.5-with-NPCBots/runs/8016133907?check_suite_focus=true

I'm not sure if there was a better way to fix the problem.

**Comment by trickerer** [comment]
Yep, there are multiple `-Werror=unused-parameter` and `-Werror=deprecated-declarations` warnings there, I guess they weren't enabled when I was updating the patch for TrinityCore.
In Visual Studio `unused parameter` warnings are disabled by default.

Fixing those warnings should fix the problem.

**Comment by trickerer** [comment]
https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/tree/Autobalance_bots

https://github.com/trickerer/TrinityCore-3.3.5-with-NPCBots/runs/8182174476?check_suite_focus=true
