### ISSUE TITLE
Нет лута с Халиона

### ISSUE THREAD

**Issue by DykeRz** [trickerer/Autobalance_for_NPCBots#7]
После убийства Халиона, ничего с него не падает
![image-6](https://github.com/trickerer/Autobalance_for_NPCBots/assets/35741241/1c74dc50-9385-467f-85ad-70fa4ffafac0)

**Comment by trickerer** [comment]
https://github.com/trickerer/Autobalance_for_NPCBots/commit/a22c2608dc538b1d9a00f479c1e2607b38bb16a9 должен пофиксить это. Хоть мне так и не удалось воспроизвести проблему
